name: artifact-download

on:
  workflow_dispatch:

permissions: read-all

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install
        run: pip install requests
      - name: Download JUnits
        run: python download_artifacts.py https://api.github.com/repos/guotin/flaky-test-ci/actions/artifacts ${{ secrets.GITHUB_TOKEN }}
      - name: Check
        run: |
          ls
