name: flaky-test-analysis

on:
  workflow_dispatch:

permissions: read-all

jobs:
  analysis:
    name: flake-score-examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Flaky test scores - grouping by days example with test_history.csv
        uses: guotin/fliprate_actions@master
        with:
          args: --test-history-csv=example_history/test_history.csv --grouping-option=days --window-size=1 --window-count=7 --top-n=5
      - name: Flaky test scores - grouping by runs example with JUnit files
        uses: guotin/fliprate_actions@master
        with:
          args: --junit-files=example_history/junit_files --grouping-option=runs --window-size=5 --window-count=3 --top-n=5
      - name: Download workflow artifacts
        run: |
          pip install requests
          python download_artifacts.py https://api.github.com/repos/guotin/flaky-test-ci/actions/artifacts ${{ secrets.GITHUB_TOKEN }}
      - name: Check files
        run: ls
      - name: Flaky test scores - grouping by runs example with downloaded workflow artifacts
        uses: guotin/fliprate_actions@master
        with:
          args: --junit-files=./ --grouping-option=runs --window-size=2 --window-count=3 --top-n=5
