name: flaky-test-analysis

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "33 * * * *"
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install .
      - name: run tests
        run: pytest --json-report || true
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: flaky-test-analysis.yml
          name: test-history
      - name: aggregate report
        run: python produce_report.py
      - name: upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-history
          path: test_history.json
